### ISSUE TITLE
Your stuff is broken

### ISSUE THREAD

**Issue by aaronscribner** [leeabc/generator-react-native-web#1]
And throws an exception trying to set the name on undefined.

**Comment by aish1550** [comment]
Getting this error too
---

Application Name:  react-native-web
? Please describe your application A base skeleton template
? Author:
? Email:
React Native Init
mv: rename /Users/aadam/projects/react-native-web/react-native-web/android to /Users/aadam/projects/react-native-web/android: No such file or directory
mv: rename /Users/aadam/projects/react-native-web/react-native-web/ios to /Users/aadam/projects/react-native-web/ios: No such file or directory
mv: /Users/aadam/projects/react-native-web/react-native-web/node_modules: No such file or directory
mv: rename /Users/aadam/projects/react-native-web/react-native-web/index.android.js to /Users/aadam/projects/react-native-web/index.android.js: No such file or directory
mv: rename /Users/aadam/projects/react-native-web/react-native-web/index.ios.js to /Users/aadam/projects/react-native-web/index.ios.js: No such file or directory
events.js:160
      throw er; // Unhandled 'error' event
      ^

**Comment by CheolminConanShin** [comment]
I had this error instead "injectResponderEventPlugin.js"
but after upgrading gradle version to 2.2-all and
upgrading and adding following dependencies
"file-loader": "^0.10.1",
"react": "~15.3.2",
"react-native": "^0.38.0"
it started working

**Comment by aaronscribner** [comment]
I believe this project is DEAD!

**Comment by binaryst4r** [comment]
I concur.

**Comment by CheolminConanShin** [comment]
I had it working with following project
https://github.com/CheolminConanShin/React_Native_Web_Mobile

**Comment by leeabc** [comment]
@aish1550 Sorry for toooooooooooo late reply this question...

I found the root cause is **"Application Name: react-native-web"** 
Due to this project is based on react-native & react-native-web.
So the project name have to follow the rules. 

"react-native-web" is not a valid name for a project. Please use a valid identifier name (**alphanumeric**)."

You can try to **remove dash "-"** and try "**reactnativeweb**" again.
That would be workable.

Sorry for tooooo late to response this issue.
